### ISSUE TITLE
Tooltips on code blocks are not located in the correct postions.

### ISSUE THREAD

**Issue by baronfel** [fslaborg/fslaborg.github.io#12]
On every page I've been to so far, the F# Formatting tooltips aren't positioned correctly near the parents.  Example: 
![image](https://cloud.githubusercontent.com/assets/573979/16095467/41af2e2a-330a-11e6-86a6-544759f2c567.png)

Here I'm hovering on 'FSharp' on line 5 of this snippet.

The tips are created statically ahead of time using the JS from `lib/tips.js`, so it seems likely that the calculations that happen in `showTip` are just incorrect.

**Comment by dsyme** [comment]
Closing this old issue. I checked with Chrome and there are now no tooltips on fslab.org, but on other linked documentation pages they are showing OK
