### ISSUE TITLE
Add tutorial: Replicate Quality Control

### ISSUE THREAD

**Issue by HLWeil** [fslaborg/fslaborg.github.io#16]
## Summary

I would like to add a tutorial about how to perform a quality control of sample replicates using:

1. [Deedle](http://bluemountaincapital.github.io/Deedle/index.html) for reading a frame containing the data
2. & 3. [FSharp.Stats](https://fslab.org/FSharp.Stats/) to impute missing values and cluster the samples
4. [CyJS.NET](https://fslab.org/Cyjs.NET/) to visualize the results

This tutorial is meant as a kind of protocol. @kMutagene should this go into the `advanced` or the `data science` category?

**Comment by kMutagene** [comment]
@HLWeil I think this fits better into the advanced category.

**Comment by bvenn** [comment]
I don't know what you are planning to do but I think there are 3 common ways to determine the sample replicability:

- histograms of coefficient of variation of the replicate groups
- column wise hierarchical clustering with subsequent analysis of cluster tree purity
- column wise PCA 

I'm curious about your visualisation using CyJS.NET 🚀 

Update: Sorry, it was not planned to close the issue 😅

**Comment by HLWeil** [comment]
## Further improve tutorial quality: 

### Code quality

```fsharp
let imputedFrame = 
    let rowKeyMap = rawFrame.RowKeys |> Seq.indexed |> Map.ofSeq
    let columnKeyMap = rawFrame.ColumnKeys |> Seq.indexed |> Map.ofSeq
    Frame.ofJaggedArray imputedData
    |> Frame.mapRowKeys (fun r -> rowKeyMap.[r])
    |> Frame.mapColKeys (fun c -> columnKeyMap.[c])
```

should be replaced with

```fsharp
let imputedFrame = 
    Frame.ofJaggedArray imputedData
    |> Frame.indexRowsWith rawFrame.RowKeys
    |> Frame.indexColsWith rawFrame.ColumnKeys
```

----------------------------------------

might this
```fsharp
// Function for flattening the cluster tree to an edgelist
let hClustToEdgeList (f : int -> 'T) (hClust : HierarchicalClustering.Cluster<'T>) =
    let rec loop (d,nodeLabel) cluster=
        match cluster with
        | HierarchicalClustering.Node (id,dist,_,c1,c2) ->
            let t = f id
            loop (dist,t) c1
            |> List.append (loop (dist,t) c2)
            |> List.append [nodeLabel,t,d] 
        | HierarchicalClustering.Leaf (_,_,label)-> [(nodeLabel,label,d)]
    loop (0., f 0) hClust
```

or something similar be something for FSharp.Stats, @bvenn?


### Spelling errors
- And it's not the best company, as `missing values` missing values
- Details about this can be found `003clusteringhierarchical.html` and (Check index and correct link)
- Missing data is `an` constant companion of many data scientists
