### ISSUE TITLE
Stale links

### ISSUE THREAD

**Issue by inputusernamehere** [fslaborg/fslaborg.github.io#25]
Hey, not sure if this is the right repo for this, but I found a couple of stale links on the website.

The "Run in Binder" and "Download script" buttons are broken in all of the tutorials linked to here: https://fslab.org/tutorials.html

**Comment by kMutagene** [comment]
Thank you, ill fix that, i assumed they work as the notebooks work =(

**Comment by inputusernamehere** [comment]
Yeah downloading the notebooks works great so I was able to explore the tutorials locally. Great presentation at dotnet focus by the way!

**Comment by kMutagene** [comment]
@inputusernamehere Thanks, really appreciate the feedback! Binder links and script download should work now as well, can you confirm that?

**Comment by inputusernamehere** [comment]
Yup, now it loads correctly!

**Comment by kMutagene** [comment]
Cool, i'll go ahead and close this then, feel free to open more issues if you have questions or hit other blockers
