### ISSUE TITLE
Compilation error in k-Means clustering tutorial

### ISSUE THREAD

**Issue by inputusernamehere** [fslaborg/fslaborg.github.io#26]
The tutorial in question: https://fslab.org/content/tutorials/002_clustering_kMeans.html

After downloading the notebook and running it locally, I get a compilation error in this code snippet:

```
clusteredIrisData
|> Seq.take 10
|> Seq.map (fun (a,b,c) -> sprintf "%i, %A, %A" a b c)
|> String.concat "\n"
|> String.concat "<br>"
|> fun x -> x + "<br> ... "
```

`Error: input.fsx (5,4)-(5,24) typecheck error The type 'string' is not compatible with the type 'seq<string>'`.

I suspect the two `String.concat`s in a row are to blame.

**Comment by bvenn** [comment]
You're right, it should be:

```F#
clusteredIrisData
|> Seq.take 10
|> Seq.map (fun (a,b,c) -> sprintf "%i, %A, %A" a b c)
|> String.concat "\n"
|> fun x -> x + "\n... "
```

It'll be fixed in a moment
