### ISSUE TITLE
Merge Branch "kevinf_01"

### ISSUE THREAD

**Issue by Freymaurer** [fslaborg/fslaborg.github.io#3]
@kMutagene i adjusted the responsivability of our previous design and added a slider. Not sure how to go ahead from there as i am not sure what the new design exactly is. Could you do this merge or give me more insight?

**Comment by kMutagene** [comment]
The classes did not change too much actually. We just removed the skew completely and renamed the colors. The color container class got removed in favor of setting bg color explicitly. That's basically it. I can take a look at your changes and cherry pick if you don't want to do that.
