### ISSUE TITLE
Separate blog and core website

### ISSUE THREAD

**Issue by kMutagene** [fslaborg/fslaborg.github.io#34]
The website takes very long to build due to the blog posts and articles. 

This should be separated into 2 projects to keep the core websizte simple and easy to develop

**Comment by 64J0** [comment]
Do we have updates on this? I want to submit PRs related to the blog posts. Must I use this repo?

**Comment by kMutagene** [comment]
@64J0 targeting this repo is correct atm, changes will carry over anyways once the separation is done.

**Comment by 64J0** [comment]
All right, thanks for the update @kMutagene

**Comment by 64J0** [comment]
Just to keep it documented:

@kMutagene added this comment about another reason to separate the blog and core website: https://github.com/fslaborg/fslaborg.github.io/pull/41#issuecomment-1173086175

**Comment by kMutagene** [comment]
Finally came around to implement this and improve things quite a bit on the way
