### ISSUE TITLE
Build is failing due to Fornax

### ISSUE THREAD

**Issue by 64J0** [fslaborg/fslaborg.github.io#44]
## Description:

The build is failing due to Fornax although it's still using the dotnet version 3.1.x apparently:

* https://github.com/fslaborg/fslaborg.github.io/runs/7169074878?check_suite_focus=true

**Comment by 64J0** [comment]
#43 must fix this issue.

**Comment by Freymaurer** [comment]
Fixed, or will be obsolete with upcoming changes to website!
