### ISSUE TITLE
`Cyjs.NET` should be changed to `Cytoscape.NET`

### ISSUE THREAD

**Issue by bvenn** [fslaborg/fslaborg.github.io#47]
Cyjs.NET was renamed to Cytoscape.NET. I only have a rough understanding, but I think the most changes must be made [here](https://github.com/fslaborg/fslaborg.github.io/blob/main/src/content/datascience-packages/cyjs.net.md):

https://www.nuget.org/packages/Cyjs.NET -> https://www.nuget.org/packages/Cytoscape.NET/

**Comment by Freymaurer** [comment]
Will be fixed with the upcoming changes!
