### ISSUE TITLE
Reduce visual noise, implement light/dark theme

### ISSUE THREAD

**Issue by kMutagene** [fslaborg/fslaborg.github.io#48]
Initially, i really liked the differently colored cards, but our color scheme has not enough contrast. I think we should rely a little bit less on color and move to a light theme that has a simple whitesmoke background and a dark theme that has the dark magenta background.

**Comment by Freymaurer** [comment]
Light/dark mode is implemented, final design will be discussed with @kMutagene when ready in #54
