### ISSUE TITLE
Tutorials page missing

### ISSUE THREAD

**Issue by Thorium** [fslaborg/fslaborg.github.io#50]
There are multiple links (both website footer and github site) to tutorials page that is returning 404.
https://fslab.org/tutorials.html

**Comment by kMutagene** [comment]
Thanks! I think the reason for this is that the [blog](https://fslab.org/blog) was called tutorials earlier, seems like i missed some links when i changed that.

**Comment by 64J0** [comment]
Is there a way to access the tutorials page using some other url for now?

**Comment by kMutagene** [comment]
it is just the blog now - although not all old posts are ported yet

**Comment by kMutagene** [comment]
should be fixed, i updated the footer component accordingly
