### ISSUE TITLE
fslab.org

### ISSUE THREAD

**Issue by dsyme** [fslaborg/fslaborg.github.io#7]
I notice https://fslab.org doesn't redirect

Should we archive existing project fslaborg.github.io and rename this to fslaborg.github.io?

**Comment by kMutagene** [comment]
There are still some things we'd like to add to the page before it can be considered 'production ready'. The current page at fslab.org is at least complete in what it tries to do, while there are still a lot of placeholders on this page. Additionally, I want to add a blog-like section for getting started/advanced tutorials for the libraries with FSharp.Formatting. When that's done, we can definitely rename this repo to   fslaborg.github.io and archive/delete the old one.

**Comment by dsyme** [comment]
ok cool :-)

**Comment by kMutagene** [comment]
the site is live now, hope you like it ;)
