### ISSUE TITLE
Use responsive max width for content containers

### ISSUE THREAD

**Issue by kMutagene** [fslaborg/fslaborg.github.io#8]
The website looks really nice on 100% width on a standard 1080p monitor, but the wider it gets (e.g. via a ultra wide display), the worse it looks because the content gets unreasonably stretched. I would suggest we revisit the responsive stylings for all classes, and maybe refactor them a bit as well (its for example hard to keep the full-width light magenta background for large screens without affecting the width of the content)

cc @Freymaurer

**Comment by Freymaurer** [comment]
Done!
