### ISSUE TITLE
Revisit image container style

### ISSUE THREAD

**Issue by kMutagene** [fslaborg/fslaborg.github.io#9]
while the responsive images scale very well when zooming **in** on the page, they behave kinda weird when zooming out/using a large screen, as the images stay the same size but all the text content gets scaled down. I'd suggest:

- removing/simplifying the hover transform
- removing the links, as the respective text content will get 'click here for more' buttons
- either upscale the text depending on vw or keep the images at fixed sizes
- some of this might be handled by #8 

cc @Freymaurer

**Comment by Freymaurer** [comment]
Done!
