### ISSUE TITLE
fslaborg.github.io/content/getting-started/index.fsx

### ISSUE THREAD

**Issue by joshualeond** [fslaborg/fslaborg.github.io#9]
I was following along with the Getting Started with FsLab and I noticed that the `School enrollment, tertiary (% gross)` doesn't exist and that `Gross enrolment ratio, tertiary, both sexes (%)` looks like the replacement.  

FsLab.0.3.17

**Comment by tpetricek** [comment]
Can you please send a PR with a fix? It seems that WorldBank likes to rename its indicators... :-/

**Comment by joshualeond** [comment]
Sure thing, I updated the indicators.

#10

**Comment by tpetricek** [comment]
Thanks!
